plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\jplap\\Documents\\Claude\\Projects\\Watchlist v4"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/watchlist.ics"

[headers.values]
Content-Type = "text/calendar; charset=utf-8"
Content-Disposition = "inline"

[[redirects]]
from = "/"
to = "/watchlist-dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/calendar"
to = "/calendar.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]