// ═══════════════════════════════════════════════════════════════════════════
// SHOW LOG DATA — the single source of truth
// Loaded by show-log.html. During a refresh, edit THIS file only.
// ═══════════════════════════════════════════════════════════════════════════

const SHOWS = [
  // ONGOING — next: upcoming season label (null = none confirmed)
  {name:"The Last of Us",                        status:"ongoing",  aired:2, next:"S3 · 2027", recheck:"2026-07-17"},
  {name:"Monarch: Legacy of Monsters",           status:"ongoing",  aired:2, next:"S3 · unannounced", recheck:"2026-07-17"},
  {name:"A Knight of the Seven Kingdoms",        status:"ongoing",  aired:1, next:"S2 · 2027", recheck:"2026-07-17"},
  {name:"It: Welcome to Derry",                  status:"ongoing",  aired:1, next:"S2 · est. 2027", recheck:"2026-07-17"},
  {name:"Splinter Cell: Deathwatch",             status:"ongoing",  aired:1, next:"S2 · 2026", recheck:"2026-07-17"},
  {name:"Alien: Earth",                          status:"ongoing",  aired:1, next:"S2 · est. 2027", recheck:"2026-07-17"},
  {name:"The Paper",                             status:"ongoing",  aired:1, next:"S2 · 9 Sep 2026"},
  {name:"Peacemaker",                            status:"ongoing",  aired:2, next:null, recheck:"2026-07-17"},
  {name:"The Studio",                            status:"ongoing",  aired:1, next:"S2 · late 2026", recheck:"2026-07-17"},
  {name:"Dexter: Resurrection",                  status:"ongoing",  aired:1, next:"S2 · Oct 2026", recheck:"2026-07-17"},
  {name:"MobLand",                               status:"ongoing",  aired:1, next:"S2 · est. late 2026", recheck:"2026-07-17"},
  {name:"Dune: Prophecy",                        status:"ongoing",  aired:1, next:"S2 · late 2026", recheck:"2026-07-17"},
  {name:"Twisted Metal",                         status:"ongoing",  aired:2, next:"S3 · est. 2027", recheck:"2026-07-17"},
  {name:"The Witcher",                           status:"ongoing",  aired:4, next:"S5 · est. Sep/Oct 2026 · final season", recheck:"2026-07-17"},
  {name:"Fallout",                               status:"ongoing",  aired:2, next:"S3 · est. mid/late 2027", recheck:"2026-07-17"},
  {name:"The Gentlemen",                         status:"ongoing",  aired:1, next:"S2 · Fall 2026", recheck:"2026-07-17"},
  {name:"Severance",                             status:"ongoing",  aired:2, next:"S3 · est. Summer 2027", recheck:"2026-07-17"},
  {name:"Rings of Power",                        status:"ongoing",  aired:2, next:"S3 · 11 Nov 2026"},
  {name:"House of the Dragon",                   status:"ongoing",  aired:3, next:"S4 · 2028", recheck:"2026-07-17", airing:"S3 · Mondays (UK)", airingUntil:"2026-08-10"},
  {name:"Ted Lasso",                             status:"ongoing",  aired:3, next:"S4 · 5 Aug 2026"},
  {name:"Ted",                                   status:"finished", aired:2},
  {name:"Tires",                                 status:"ongoing",  aired:2, next:"S3 · 13 Aug 2026"},
  {name:"The Boys",                              status:"finished", aired:5, next:null},
  {name:"Vought Rising",                         status:"ongoing",  aired:0, next:"S1 · est. early 2027", recheck:"2026-07-17", poster:"Images/vought-rising-poster.avif"},
  {name:"Alley Cats",                            status:"ongoing",  aired:0, next:"S1 · 7 Aug 2026"},
  {name:"Stranger Things: Tales from '85",       status:"ongoing",  aired:1, next:"S2 · Fall 2026", recheck:"2026-07-17"},
  {name:"Welcome to Wrexham",                    status:"ongoing",  aired:5, next:"S6 · 27 May 2027"},
  {name:"Spider-Noir",                           status:"ongoing",  aired:1, next:"S2 · unannounced", recheck:"2026-07-17"},
  {name:"Your Friendly Neighbourhood Spider-Man",status:"ongoing",  aired:1, next:"S2 · Fall 2026", recheck:"2026-07-17"},
  {name:"Daredevil: Born Again",                 status:"ongoing",  aired:2, next:"S3 · Mar 2027", recheck:"2026-07-17"},
  {name:"Ahsoka",                                status:"ongoing",  aired:1, next:"S2 · early 2027", recheck:"2026-07-17"},
  {name:"The Mandalorian",                       status:"finished", aired:3},
  {name:"Maul: Shadow Lord",                     status:"ongoing",  aired:1, next:"S2 · est. late 2027", recheck:"2026-07-17"},
  {name:"SAS: Rogue Heroes",                     status:"ongoing",  aired:2, next:"S3 · est. late 2026", recheck:"2026-07-17"},
  // ENDED (finished)
  {name:"Extras",                                   status:"finished", aired:2},
  {name:"Derek",                                    status:"finished", aired:2},
  {name:"After Life",                               status:"finished", aired:3},
  {name:"Dave",                                     status:"finished", aired:3},
  {name:"Squid Game",                               status:"finished", aired:3},
  {name:"Ozark",                                    status:"finished", aired:4},
  {name:"Heroes",                                status:"finished", aired:4},
  {name:"See",                                   status:"finished", aired:3},
  {name:"Game of Thrones",                       status:"finished", aired:8},
  {name:"The Sopranos",                          status:"finished", aired:6},
  {name:"Breaking Bad",                          status:"finished", aired:5},
  {name:"Stranger Things",                       status:"finished", aired:5},
  {name:"Friends",                               status:"finished", aired:10},
  {name:"The Flight Attendant",                  status:"finished", aired:2},
  {name:"Prison Break",                          status:"finished", aired:5},
  {name:"The Walking Dead",                      status:"finished", aired:11},
  {name:"Better Call Saul",                      status:"finished", aired:6},
  {name:"Dexter",                                status:"finished", aired:8},
  {name:"Arcane",                                status:"finished", aired:2},
  {name:"Succession",                            status:"finished", aired:4},
  {name:"Peaky Blinders",                        status:"finished", aired:6},
  {name:"Spartacus",                             status:"finished", aired:4},
  {name:"Oz",                                    status:"finished", aired:6},
  {name:"Trailer Park Boys",                     status:"finished", aired:12},
  {name:"The Office (US)",                       status:"finished", aired:9},
  {name:"The Office (UK)",                       status:"finished", aired:2, imdbId:"tt0290978"},
  {name:"Lost",                                  status:"finished", aired:6},
  {name:"Star Wars: The Clone Wars",             status:"finished", aired:7},
  {name:"Star Wars: Rebels",                     status:"finished", aired:4},
  {name:"Star Wars: Resistance",                 status:"finished", aired:2},
  {name:"Andor",                                 status:"finished", aired:2},
  {name:"The Bad Batch",                         status:"finished", aired:3},
  {name:"Loki",                                  status:"finished", aired:2},
  {name:"What If…?",                             status:"finished", aired:3},
  // ENDED (cancelled)
  {name:"Agent Carter",                          status:"cancelled",aired:2},
  {name:"Halo",                                  status:"cancelled",aired:2},
  {name:"Raised by Wolves",                      status:"cancelled",aired:2},
  {name:"Gen V",                                 status:"cancelled",aired:2},
  {name:"Westworld",                             status:"cancelled",aired:4},
];
