@echo off
echo Stopping any existing watcher...
powershell -Command "Get-WmiObject Win32_Process | Where-Object { $_.CommandLine -like '*watch-and-push.ps1*' -and $_.ProcessId -ne $PID } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }" 2>nul
echo Starting watcher...
powershell -NoExit -ExecutionPolicy Bypass -File "%~dp0watch-and-push.ps1"
